name: Supabase Keepalive

on:
  schedule:
    # Roda automaticamente todos os dias ao meio-dia (UTC)
    - cron: '0 12 * * *'
  workflow_dispatch: # Permite rodar manualmente se necessario

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Acordar Supabase
        run: |
          echo "Enviando ping para o banco de dados..."
          curl -s -o /dev/null -w "HTTP Status: %{http_code}" \
          -H "apikey: sb_publishable_ujOgrDJiP7ITpMRtfYRfuw_WagffxIl" \
          -H "Authorization: Bearer sb_publishable_ujOgrDJiP7ITpMRtfYRfuw_WagffxIl" \
          "https://ibickxigovgcwwsqfpeb.supabase.co/rest/v1/songs?limit=1"
          echo -e "\nPing enviado com sucesso!"
